sudo: false
language: node_js
node_js:
  - '4'
  - iojs
install:
  - npm install
  - npm install -g gulp
  - npm install -g firebase-tools
script:
  - npm test
  - npm run build
after_success:
  - firebase deploy --token "${FIREBASE_TOKEN}"

