sudo: false
language: node_js
node_js:
  - '4'
  - iojs
before_script:
  - npm install -g gulp
script:
  - npm run build
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token "${FIREBASE_TOKEN}"

